# Generated by Django 5.0.4 on 2024-05-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_panier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panier',
            name='description',
            field=models.CharField(max_length=200000),
        ),
    ]
