# Generated by Django 5.0.4 on 2024-05-21 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_panier_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommended_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('title', models.CharField(max_length=2000)),
                ('img_link', models.CharField(max_length=2000)),
                ('price', models.CharField(max_length=2000)),
                ('rating', models.CharField(max_length=2000)),
                ('reviews', models.CharField(max_length=20000)),
                ('availability', models.CharField(max_length=200000)),
                ('description', models.CharField(max_length=2000000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
