# Generated by Django 5.0.4 on 2024-05-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_clustered_products_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clustered_products',
            name='product_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
