# Generated by Django 5.0.4 on 2024-05-22 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_clustered_products_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panier',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panier', to='app.products'),
        ),
    ]
