# Generated by Django 5.0.4 on 2024-05-28 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_productdetails_user_productsforme'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productsforme',
            new_name='ALL_products',
        ),
    ]
