# Generated by Django 5.0.4 on 2024-05-28 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_products_popular_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetails',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productdetails',
            name='user',
        ),
        migrations.DeleteModel(
            name='Clustered_Products_Details',
        ),
        migrations.DeleteModel(
            name='ProductDetails',
        ),
    ]
